name: sms_plugin
description: "Plug in for send and Resive sms"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sms_plugin
        pluginClass: SmsPlugin
